# playbook.yml
---
- name: configure and deploy the webservers and application code
  hosts: all
  user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
    - vars.yml

  roles:
    - web

  tasks:
    - name: mysql | Install package/s
      apt: pkg={{ item }} state=installed update_cache=yes
      with_items:
        - mysql-server
        - python-mysqldb # needed for ansibles mysql support

    - name: mysql | Ensure MySql is running
      action: service name=mysql state=started

    - name: composer | Install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer

    - name: composer | Rename composer.phar to composer
      command: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

    - name: composer | Make composer executable
      file: path=/usr/local/bin/composer mode=0755

    - name: 3. start Apache
      service: name=apache2 state=running enabled=yes

    - name: apache | xdebug
      template:
        src: xdebug.j2
        dest: "/etc/php5/mods-available/xdebug.ini"
        owner: root
        group: root
        mode: 0644
      notify:
        - restart apache2

    - name: chsh
      shell: chsh -s /bin/bash www-data