# General apache config
# 1. install apache
# 2. enable modules (e.g., ssl, rewrite)
# 3. add vhost(s)
# 4. add ssl vhost(s)
# 5. enable sites
# 6. enable default ssl site
# 7. enable ssl sites
- name: Apache | install
  apt: name=apache2 state=present update_cache=yes
  notify:
    - restart apache2

- name: Apache | enable module(s)
  action: command a2enmod {{ item }}
  with_items:
    - ssl
    - rewrite
  notify:
      - restart apache2

- name: Apache | add vhost(s)
  template:
    src: '../templates/template.conf.j2'
    dest: "/etc/apache2/sites-available/{{item.dest}}.conf"
  with_items: vhost
  notify:
    - restart apache2

- name: Apache | add ssl vhost(s)
  template:
    src: '../templates/template-ssl.conf.j2'
    dest: "/etc/apache2/sites-available/{{item.dest}}-ssl.conf"
  with_items: vhost
  notify:
    - restart apache2

- name: Apache | enable sites
  action: command a2ensite {{item.dest}}
  with_items: vhost
  notify:
    - restart apache2

- name: Apache | enable default ssl site
  action: command a2ensite default-ssl
  notify:
    - restart apache2

- name: Apache | enable ssl sites
  action: "command a2ensite {{item.dest}}-ssl"
  when: item.ssl
  with_items: vhost
  notify:
    - restart apache2
