- name: Apache | Install
  apt: name=apache2 state=present
  notify:
    - restart apache2

- name: Apache | Enable ssl module
  action: command a2enmod ssl
  notify:
      - restart apache2

- name: Apache | Enable rewrite module
  action: command a2enmod rewrite
  notify:
      - restart apache2

- name: apache | add vhost(s)
  template:
    src: '../templates/template.conf.j2'
    dest: "/etc/apache2/sites-available/{{item.dest}}.conf"
  with_items: webconfig
  notify:
    - restart apache2

- name: apache | add ssl vhost(s)
  template:
    src: '../templates/template-ssl.conf.j2'
    dest: "/etc/apache2/sites-available/{{item.dest}}-ssl.conf"
  with_items: webconfig
  notify:
    - restart apache2

#- name: Apache | enable sites
#  action: command a2ensite default-ssl
#  with_items: webconfig
#  notify:
#    - restart apache2

- name: Apache | enable sites
  action: command a2ensite {{item.dest}}
  with_items: webconfig
  notify:
    - restart apache2

- name: Apache | enable ssl sites
  action: "command a2ensite {{item.dest}}-ssl"
  with_items: webconfig
  notify:
    - restart apache2
